<a href="https://colab.research.google.com/github/Daddy-senpaii/MLP-from-scratch/blob/main/Moon_Project_Tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
pip install tensorflow

In [3]:
from sklearn.datasets import make_moons

X, y = make_moons(n_samples = 60000, noise = 0.2, random_state = 42)

In [7]:
print("X shape is: ",X.shape)
y = y.reshape(1, y.shape[0])
print("Y shape is: ", y.shape)

X shape is:  (60000, 2)
Y shape is:  (1, 60000)


In [9]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

In [11]:
physical_devices = tf.config.list_logical_devices("GPU")
if physical_devices:
  tf.config.experimental.set_memory_growth(physical_devices[0], True)
else:
  print("No GPU devices found")

No GPU devices found


In [20]:
model = keras.Sequential(
    [
        layers.Dense(10, activation = "relu" , input_shape = (2,)),
        layers.Dense(10, activation = "relu"),
        layers.Dense(10, activation = "relu"),
        layers.Dense(10, activation = "relu"),
        layers.Dense(10, activation = "relu"),
        layers.Dense(1, activation = "sigmoid"),
    ]
)

# Explicitly build the model
model.build(input_shape=(None, 2))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [21]:
model.compile(
    loss = keras.losses.BinaryCrossentropy(),
    optimizer = keras.optimizers.Adam(learning_rate = 0.001),
    metrics = ["accuracy"]
)

In [22]:
model.fit(X, y.T, batch_size=30, epochs = 100, verbose = 2)

Epoch 1/100
2000/2000 - 6s - 3ms/step - accuracy: 0.9438 - loss: 0.1488
Epoch 2/100
2000/2000 - 5s - 2ms/step - accuracy: 0.9696 - loss: 0.0817
Epoch 3/100
2000/2000 - 4s - 2ms/step - accuracy: 0.9700 - loss: 0.0800
Epoch 4/100
2000/2000 - 4s - 2ms/step - accuracy: 0.9701 - loss: 0.0797
Epoch 5/100
2000/2000 - 5s - 2ms/step - accuracy: 0.9700 - loss: 0.0796
Epoch 6/100
2000/2000 - 4s - 2ms/step - accuracy: 0.9701 - loss: 0.0796
Epoch 7/100
2000/2000 - 5s - 2ms/step - accuracy: 0.9699 - loss: 0.0791
Epoch 8/100
2000/2000 - 4s - 2ms/step - accuracy: 0.9698 - loss: 0.0796
Epoch 9/100
2000/2000 - 4s - 2ms/step - accuracy: 0.9701 - loss: 0.0789
Epoch 10/100
2000/2000 - 4s - 2ms/step - accuracy: 0.9703 - loss: 0.0787
Epoch 11/100
2000/2000 - 5s - 3ms/step - accuracy: 0.9704 - loss: 0.0789
Epoch 12/100
2000/2000 - 4s - 2ms/step - accuracy: 0.9700 - loss: 0.0782
Epoch 13/100
2000/2000 - 4s - 2ms/step - accuracy: 0.9698 - loss: 0.0787
Epoch 14/100
2000/2000 - 4s - 2ms/step - accuracy: 0.9700 - 

In [23]:
X_test , y_test = make_moons(n_samples = 10000, noise = 0.2, random_state = 42)


In [25]:
model.evaluate(X_test, y_test, verbose=2)

313/313 - 1s - 3ms/step - accuracy: 0.9736 - loss: 0.0723


[0.0723082423210144, 0.9735999703407288]

In [36]:
X_data, y_data = make_moons(n_samples = 10, noise = 0.2, random_state = 42)

In [37]:
print(X_data)
print(y_data)

[[ 1.76291504 -0.00500372]
 [ 0.59093115  0.60207282]
 [-0.11427603  0.31518343]
 [ 0.4774902   0.19007394]
 [ 1.16328902 -0.8047752 ]
 [-0.08560921  0.85151863]
 [ 1.85933124  0.07207587]
 [-1.12589499  0.11954409]
 [-0.19520917  0.78595339]
 [ 0.31733705 -0.31019391]]
[1 0 1 0 1 0 1 0 0 1]


In [38]:
model.evaluate(X_data, y_data, verbose = 2)

y_pred_prob = model.predict(X_data)
y_pred = (y_pred_prob > 0.5).astype(int)
print(y_pred)

1/1 - 0s - 37ms/step - accuracy: 0.9000 - loss: 0.1713
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step
[[1]
 [0]
 [1]
 [1]
 [1]
 [0]
 [1]
 [0]
 [0]
 [1]]
